version: "3"
services: 
    mongodb:
      image : mongo:5.0.5
      volumes:
      - ./mongo_data:/data/db
      ports:
      - 27017:27017
    device-api:
        build: 
          context: .
          dockerfile: Dockerfile
        environment:
          - MongoSettings__MongoConnectionString=mongodb://mongodb
        image: "device-api"
        ports:
          - "9199:9199"
        volumes: 
          - ./device-api:/logs/device-api